### ISSUE TITLE
None of these files exist './src/Alert'

### ISSUE THREAD

**Issue by perrin-lucas** [Blaumaus/react-native-redux-alert#1]
package.json
```
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-redux": "^7.2.4",
    "redux": "^4.1.0",
    "react-native-redux-alert": "^1.0.1",
```
I've followed the [usage](https://github.com/Blaumaus/react-native-redux-alert#usage) section 

I have this error when launching the application

![image](https://user-images.githubusercontent.com/42546473/127930561-058df05d-a9b3-4412-9559-f8921e3552df.png)

Is it possible to run the application with this version of react-native?

If not, would it be possible to make it compatible with older versions?

Thanks 😉

**Comment by HectorFerris** [comment]
Same problem!

**Comment by Blaumaus** [comment]
This issue will be fixed in a few days. Thanks for the report.

**Comment by Blaumaus** [comment]
@xlucxs, @HectorFerris the issue seems to be fixed. Please, try to use v1.0.5

**Comment by Blaumaus** [comment]
Closing issue as it seems to be fixed. Please, open a new one or write here if you still have any problems described above.
